version: '3.7'
services:
  server:
    container_name: ethstats-network-server
    image: alethio/ethstats-network-server:latest
    restart: always
    depends_on:
      - deepstream
    ports:
      - 0.0.0.0:3000:3000
      - 0.0.0.0:3030:3030
      - 0.0.0.0:8888:8888
    environment:
      - NETWORK_ID=42001
      - NETWORK_NAME=helios
      - LITE=1
      - LITE_DB_PERSIST=0
      - LITE_API_PORT=3030
      - APP_PORT=3000
      - METRICS_PORT=8888
      - DEEPSTREAM_HOST=deepstream
    command: ["./bin/app.js", "-v"]
  deepstream:
    container_name: ethstats-network-deepstream
    image: deepstreamio/deepstream.io:3.2.2
    restart: always
    ports:
      - 0.0.0.0:6020:6020
